
local function dBoss(msg)


if msg.text then
if msg.text == "زخرفه" then
redis:setex(boss..":ZhrfNow"..msg.sender_user_id,500,true)
sendMsg(msg.chat_id,msg.id,"📑| حسننا , الان يمكنك ارسال الاسم 💯")    
return false
end

if redis:get(boss..":ZhrfNow"..msg.sender_user_id) then
local End_Text = {
' •🌱💚﴿ֆ ❥',
'🍿﴿ֆ ❥',
'• 🌸💸 ❥˓  ',
'🖤🌞﴿ֆ',
' • 🐼🌿﴾ֆ',
' •🙊💙﴿ֆ ❥', 
'-💁🏼‍♂️✨﴿ֆ ❥ ', 
'•|• 〄💖‘',
' ⚡️🌞 •|•℡', 
'- ⁽🙆‍♂️✨₎ֆ', 
'❥┇💁🏼‍♂️🔥“', 
'💜💭℡ֆ', 
'-┆💙🙋🏼‍♂️♕', 
'- ⁽🙆🏻🍿₎ֆ',
'“̯ 🐼💗 |℡',
'⁞ 🐝🍷',
'┋⁽❥̚͢₎ 🐣💗', 
'•|• ✨🌸‘',
'  ֆ 💭💔ۦ',
'ֆ 💛💭ۦ', 
'ֆ ⚡️🔱ۦ',
'℡ᴖ̈💜✨⋮', 
'⋮⁽🌔☄️₎ۦ˛',
'⁞❉💥┋♩',
' ⁞✦⁽☻🔥₎“ٰۦ',
'℡ ̇₎ ✨🐯⇣✦',
'⁞♩⁽🌞🌩₎⇣✿',
'ۦٰ‏┋❥ ͢˓🦁💛ۦ‏',
'⚡️♛ֆ₎',
'♛⇣🐰☄️₎✦',
'⁾⇣✿💖┊❥',
' ₎✿💥😈 ⁞“❥', 
'😴🌸✿⇣',
'❥┊⁽ ℡🦁🌸'
}

local End_Text = {
'║👹💥ᵛ͢ᵎᵖ ⌯﴾❥',
'₎🐳🍥۶ֆ',
'♩┊💎🌸❥ ₎',
'₎❁😻🌸⇣',
'┊🏻“👄🌺) ℡',
'❥ֆ☄⚡️ ᴗ̈',
'❥•َ⚡️ْ🦇️͢ֆ⸽',
'♜🌸🐝 ⁞',
'║♜💛⚡️͢₎⇣✿ ⁞',
'⌯⇣✿💙☄ ⁞﴾❥',
'¦⇣👽♜͢ ⁞',
'❥•َْ👻⚡️͢⸽۶ֆ',
'ֆ⸽♜👹🔥͢₎⇣',
'⌯⇣✿💙☄ ⁞﴾❥',
'♛⌗👽ᵛ🚀﴾⌯',
' ❀🎼🌸℡³¹³',
' ⁞ 🐝🍷',
'• 🐼🌿﴾ֆ',
'🐳🍥۶',
'┊※🏎️‘’💛',
'❥┊⁽ ℡🦁🌸',
'😴🌸✿⇣',
'₎❁😻🌸⇣',
'💁🏼‍♂️✨﴿ֆ ❥',
'┆💙🙋🏼‍♂️♕',
'➤🙇🏼ֆ﴾',
'˛⁽💆🏻‍♂🌙₎⇣✿',
'ཻ ☫ٰ⇣🐼💙ֆ℠',
'℡ 🌞🔥‎‏ ⁾┊',
'┊💎🌸❥ ₎',
'∬💛✨ֆ',
'🌸💸 ❥˓',
' ⁽࿑♚꫶😼ֆ﴾',
'❥•َ⚡️🦇️ֆ⸽',
'🍿﴿ֆ ❥',
'ᵛ͢ᵎᵖ📯💛﴾'
}


local Text = " اهلا وسهلا "


local Zhrf = Text:gsub('ا','Ȋ')
Zhrf = Zhrf:gsub('ب','ɹ̣')
Zhrf = Zhrf:gsub('ت','ɹ̈')
Zhrf = Zhrf:gsub('ث','ɹ̈̇')
Zhrf = Zhrf:gsub('ج','ᓗฺ')
Zhrf = Zhrf:gsub('ح','ᓗ')
Zhrf = Zhrf:gsub('خ','ᓘ')
Zhrf = Zhrf:gsub('د','כ')
Zhrf = Zhrf:gsub('ذ','כ֗')
Zhrf = Zhrf:gsub('ر','ȷ')
Zhrf = Zhrf:gsub('ز','j')
Zhrf = Zhrf:gsub('س','ɹɹɹ')
Zhrf = Zhrf:gsub('ش','ɹɹ̈̇ɹ')
Zhrf = Zhrf:gsub('ص','ᘗ')
Zhrf = Zhrf:gsub('ض','ᘞ̇')
Zhrf = Zhrf:gsub('ط','Ь')
Zhrf = Zhrf:gsub('ظ','Ь̇')
Zhrf = Zhrf:gsub('ع','ϛ')
Zhrf = Zhrf:gsub('غ','ϛ۬')
Zhrf = Zhrf:gsub('ف','ᓅ')
Zhrf = Zhrf:gsub('ق','ᓆ')
Zhrf = Zhrf:gsub('ك','丂')
Zhrf = Zhrf:gsub('ل','⅃')
Zhrf = Zhrf:gsub('م','ᓄ')
Zhrf = Zhrf:gsub('ن','ᓢ')
Zhrf = Zhrf:gsub('ه','බ')
Zhrf = Zhrf:gsub('و','g')
Zhrf = Zhrf:gsub('ي','ɹ̤')
Zhrf = Zhrf:gsub('a','ᗩ')
Zhrf = Zhrf:gsub('A','ᗩ')
Zhrf = Zhrf:gsub("b","ᗷ")
Zhrf = Zhrf:gsub("B","ᗷ")
Zhrf = Zhrf:gsub("c","ᑕ")
Zhrf = Zhrf:gsub("C","ᑕ")
Zhrf = Zhrf:gsub("d","ᗪ")
Zhrf = Zhrf:gsub("D","ᗪ")
Zhrf = Zhrf:gsub("e","E")
Zhrf = Zhrf:gsub("E","E")
Zhrf = Zhrf:gsub("f","ᖴ")
Zhrf = Zhrf:gsub("F","ᖴ")
Zhrf = Zhrf:gsub("g","G")
Zhrf = Zhrf:gsub("G","G")
Zhrf = Zhrf:gsub("h","ᕼ")
Zhrf = Zhrf:gsub("H","ᕼ")
Zhrf = Zhrf:gsub("i","I")
Zhrf = Zhrf:gsub("I","I")
Zhrf = Zhrf:gsub("j","ᒍ")
Zhrf = Zhrf:gsub("J","ᒍ")
Zhrf = Zhrf:gsub("k","K")
Zhrf = Zhrf:gsub("K","K")
Zhrf = Zhrf:gsub("l","ᒪ")
Zhrf = Zhrf:gsub("L","ᒪ")
Zhrf = Zhrf:gsub("m","ᗰ")
Zhrf = Zhrf:gsub("M","ᗰ")
Zhrf = Zhrf:gsub("n","ᑎ")
Zhrf = Zhrf:gsub("N","ᑎ")
Zhrf = Zhrf:gsub("o","O")
Zhrf = Zhrf:gsub("O","O")
Zhrf = Zhrf:gsub("p","ᑭ")
Zhrf = Zhrf:gsub("P","ᑭ")
Zhrf = Zhrf:gsub("q","ᑫ")
Zhrf = Zhrf:gsub("Q","ᑫ")
Zhrf = Zhrf:gsub("r","ᖇ")
Zhrf = Zhrf:gsub("R","ᖇ")
Zhrf = Zhrf:gsub("s","ᔕ")
Zhrf = Zhrf:gsub("S","ᔕ")
Zhrf = Zhrf:gsub("t","T")
Zhrf = Zhrf:gsub("T","T")
Zhrf = Zhrf:gsub("u","ᑌ")
Zhrf = Zhrf:gsub("U","ᑌ")
Zhrf = Zhrf:gsub("v","ᐯ")
Zhrf = Zhrf:gsub("V","ᐯ")
Zhrf = Zhrf:gsub("w","ᗯ")
Zhrf = Zhrf:gsub("W","ᗯ")
Zhrf = Zhrf:gsub("x","᙭")
Zhrf = Zhrf:gsub("X","᙭")
Zhrf = Zhrf:gsub("y","Y")
Zhrf = Zhrf:gsub("Y","Y")
Zhrf = Zhrf:gsub("z","ᘔ")
Zhrf = Zhrf:gsub("Z","ᘔ")


local Zhrf2 = Text:gsub('ض','ضِـٰٚـِْ✮ِـٰٚـِْ')
Zhrf2 = Zhrf2:gsub('ص','صِـٰٚـِْ✮ِـٰٚـِْ')
Zhrf2 = Zhrf2:gsub('ث','ثِـٰٚـِْ✮ِـٰٚـِْ')
Zhrf2 = Zhrf2:gsub('ق','قِـٰٚـِْ✮ِـٰٚـِْ')
Zhrf2 = Zhrf2:gsub('ف','فِ͒ـٰٚـِْ✮ِـٰٚـِْ')
Zhrf2 = Zhrf2:gsub('غ','غِـٰٚـِْ✮ِـٰٚـِْ')
Zhrf2 = Zhrf2:gsub('ع','عِـٰٚـِْ✮ِـٰٚـِْ')
Zhrf2 = Zhrf2:gsub('خ','خِ̐ـٰٚـِْ✮ِـٰٚـِْ')
Zhrf2 = Zhrf2:gsub('ح','حِـٰٚـِْ✮ِـٰٚـِْ')
Zhrf2 = Zhrf2:gsub('ج','جِـٰٚـِْ✮ِـٰٚـِْ')
Zhrf2 = Zhrf2:gsub('ش','شِـٰٚـِْ✮ِـٰٚـِْ')
Zhrf2 = Zhrf2:gsub('س','سِـٰٚـِْ✮ِـٰٚـِْ')
Zhrf2 = Zhrf2:gsub('ي','يِـٰٚـِْ✮ِـٰٚـِْ')
Zhrf2 = Zhrf2:gsub('ب','بِـٰٚـِْ✮ِـٰٚـِْ')
Zhrf2 = Zhrf2:gsub('ل','لِـٰٚـِْ✮ِـٰٚـِْ')
Zhrf2 = Zhrf2:gsub('ا','آ')
Zhrf2 = Zhrf2:gsub('ت','تِـٰٚـِْ✮ِـٰٚـِْ')
Zhrf2 = Zhrf2:gsub('ن','نِـٰٚـِْ✮ِـٰٚـِْ')
Zhrf2 = Zhrf2:gsub('م','مِـٰٚـِْ✮ِـٰٚـِْ')
Zhrf2 = Zhrf2:gsub('ك','ڪِـٰٚـِْ✮ِـٰٚـِْ')
Zhrf2 = Zhrf2:gsub('ط','طِـٰٚـِْ✮ِـٰٚـِْ')
Zhrf2 = Zhrf2:gsub('ذ','ذِـٰٚـِْ✮ِـٰٚـِْ')
Zhrf2 = Zhrf2:gsub('ظ','ظِـٰٚـِْ✮ِـٰٚـِْ')
Zhrf2 = Zhrf2:gsub('ء','ء')
Zhrf2 = Zhrf2:gsub('ؤ','ؤ')
Zhrf2 = Zhrf2:gsub('ر','ر')
Zhrf2 = Zhrf2:gsub('ى','ى')
Zhrf2 = Zhrf2:gsub('ز','ز')
Zhrf2 = Zhrf2:gsub('ظ','ظِـٰٚـِْ✮ِـٰٚـِْ')
Zhrf2 = Zhrf2:gsub('و','ﯛ̲୭')
Zhrf2 = Zhrf2:gsub("ه", "ۿۿہ")
Zhrf2 = Zhrf2:gsub('a','•🇦')
Zhrf2 = Zhrf2:gsub('A','•🇦')
Zhrf2 = Zhrf2:gsub("b","•🇧")
Zhrf2 = Zhrf2:gsub("B","•🇧")
Zhrf2 = Zhrf2:gsub("c","•🇨")
Zhrf2 = Zhrf2:gsub("C","•🇨")
Zhrf2 = Zhrf2:gsub("d","•🇩")
Zhrf2 = Zhrf2:gsub("D","•🇩")
Zhrf2 = Zhrf2:gsub("e","•🇪")
Zhrf2 = Zhrf2:gsub("E","•🇪")
Zhrf2 = Zhrf2:gsub("f","•🇫")
Zhrf2 = Zhrf2:gsub("F","•🇫")
Zhrf2 = Zhrf2:gsub("g","•🇬")
Zhrf2 = Zhrf2:gsub("G","•🇬")
Zhrf2 = Zhrf2:gsub("h","•🇭")
Zhrf2 = Zhrf2:gsub("H","•🇭")
Zhrf2 = Zhrf2:gsub("i","•🇮")
Zhrf2 = Zhrf2:gsub("I","•🇮")
Zhrf2 = Zhrf2:gsub("j","•🇯")
Zhrf2 = Zhrf2:gsub("J","•🇯")
Zhrf2 = Zhrf2:gsub("k","•🇰")
Zhrf2 = Zhrf2:gsub("K","•🇰")
Zhrf2 = Zhrf2:gsub("l","•🇱")
Zhrf2 = Zhrf2:gsub("L","•🇱")
Zhrf2 = Zhrf2:gsub("m","•🇲")
Zhrf2 = Zhrf2:gsub("M","•🇲")
Zhrf2 = Zhrf2:gsub("n","•🇳")
Zhrf2 = Zhrf2:gsub("N","•🇳")
Zhrf2 = Zhrf2:gsub("o","•🇴")
Zhrf2 = Zhrf2:gsub("O","•🇴")
Zhrf2 = Zhrf2:gsub("p","•🇵")
Zhrf2 = Zhrf2:gsub("P","•🇵")
Zhrf2 = Zhrf2:gsub("q","•🇶")
Zhrf2 = Zhrf2:gsub("Q","•🇶")
Zhrf2 = Zhrf2:gsub("r","•🇷")
Zhrf2 = Zhrf2:gsub("R","•🇷")
Zhrf2 = Zhrf2:gsub("s","•🇸")
Zhrf2 = Zhrf2:gsub("S","•🇸")
Zhrf2 = Zhrf2:gsub("t","•🇹")
Zhrf2 = Zhrf2:gsub("T","•🇹")
Zhrf2 = Zhrf2:gsub("u","•🇻")
Zhrf2 = Zhrf2:gsub("U","•🇻")
Zhrf2 = Zhrf2:gsub("v","•🇺")
Zhrf2 = Zhrf2:gsub("V","•🇺")
Zhrf2 = Zhrf2:gsub("w","•🇼")
Zhrf2 = Zhrf2:gsub("W","•🇼")
Zhrf2 = Zhrf2:gsub("x","•🇽")
Zhrf2 = Zhrf2:gsub("X","•🇽")
Zhrf2 = Zhrf2:gsub("y","•🇾")
Zhrf2 = Zhrf2:gsub("Y","•🇾")
Zhrf2 = Zhrf2:gsub("z","•🇿")
Zhrf2 = Zhrf2:gsub("Z","•🇿")
Zhrf2 = Zhrf2:gsub("1","•🇿")



local Zhrf3 = Text:gsub('ض','ضِٰـِۢ')
Zhrf3 = Zhrf3:gsub('ص','صِٰـِۢ')
Zhrf3 = Zhrf3:gsub('ث','ثِٰـِۢ')
Zhrf3 = Zhrf3:gsub('ق','قِٰـِۢ')
Zhrf3 = Zhrf3:gsub('ف','فِٰ͒ـِۢ')
Zhrf3 = Zhrf3:gsub('غ','غِٰـِۢ')
Zhrf3 = Zhrf3:gsub('ع','عِٰـِۢ')
Zhrf3 = Zhrf3:gsub('خ','خِٰ̐ـِۢ')
Zhrf3 = Zhrf3:gsub('ح','حِٰـِۢ')
Zhrf3 = Zhrf3:gsub('ج','جِٰـِۢ')
Zhrf3 = Zhrf3:gsub('ش','شِٰـِۢ')
Zhrf3 = Zhrf3:gsub('س','سِٰـِۢ')
Zhrf3 = Zhrf3:gsub('ي','يِٰـِۢ')
Zhrf3 = Zhrf3:gsub('ب','بِٰـِۢ')
Zhrf3 = Zhrf3:gsub('ل','لِٰـِۢ')
Zhrf3 = Zhrf3:gsub('ا','آ')
Zhrf3 = Zhrf3:gsub('ت','تِٰـِۢ')
Zhrf3 = Zhrf3:gsub('ن','نِٰـِۢ')
Zhrf3 = Zhrf3:gsub('م','مِٰـِۢ')
Zhrf3 = Zhrf3:gsub('ك','ڪِٰـِۢ')
Zhrf3 = Zhrf3:gsub('ط','طِٰـِۢ')
Zhrf3 = Zhrf3:gsub('ظ','ظِٰـِۢ')
Zhrf3 = Zhrf3:gsub('ء','ء')
Zhrf3 = Zhrf3:gsub('ؤ','ؤ')
Zhrf3 = Zhrf3:gsub('ر','ر')
Zhrf3 = Zhrf3:gsub('ى','ى')
Zhrf3 = Zhrf3:gsub('ز','ز')
Zhrf3 = Zhrf3:gsub('و','ﯛ̲୭')
Zhrf3 = Zhrf3:gsub('ه','ۿۿہ')
Zhrf3 = Zhrf3:gsub('a','Ꭿ')
Zhrf3 = Zhrf3:gsub('A','Ꭿ')
Zhrf3 = Zhrf3:gsub("b","Ᏸ")
Zhrf3 = Zhrf3:gsub("B","Ᏸ")
Zhrf3 = Zhrf3:gsub("c","Ꮸ")
Zhrf3 = Zhrf3:gsub("C","Ꮸ")
Zhrf3 = Zhrf3:gsub("d","Ꮷ")
Zhrf3 = Zhrf3:gsub("D","Ꮷ")
Zhrf3 = Zhrf3:gsub("e","Ꮛ")
Zhrf3 = Zhrf3:gsub("E","Ꮛ")
Zhrf3 = Zhrf3:gsub("f","Ꭶ")
Zhrf3 = Zhrf3:gsub("F","Ꭶ")
Zhrf3 = Zhrf3:gsub("g","Ᏻ")
Zhrf3 = Zhrf3:gsub("G","Ᏻ")
Zhrf3 = Zhrf3:gsub("h","Ᏺ")
Zhrf3 = Zhrf3:gsub("H","Ᏺ")
Zhrf3 = Zhrf3:gsub("i","Ꭸ")
Zhrf3 = Zhrf3:gsub("I","Ꭸ")
Zhrf3 = Zhrf3:gsub("j","Ꮰ")
Zhrf3 = Zhrf3:gsub("J","Ꮰ")
Zhrf3 = Zhrf3:gsub("k","Ꮵ")
Zhrf3 = Zhrf3:gsub("K","Ꮵ")
Zhrf3 = Zhrf3:gsub("l","Ꮭ")
Zhrf3 = Zhrf3:gsub("L","Ꮭ")
Zhrf3 = Zhrf3:gsub("m","ᗰ")
Zhrf3 = Zhrf3:gsub("M","ᗰ")
Zhrf3 = Zhrf3:gsub("n","Ꮑ")
Zhrf3 = Zhrf3:gsub("N","Ꮑ")
Zhrf3 = Zhrf3:gsub("o","Ꭷ")
Zhrf3 = Zhrf3:gsub("O","Ꭷ")
Zhrf3 = Zhrf3:gsub("p","Ꭾ")
Zhrf3 = Zhrf3:gsub("P","Ꭾ")
Zhrf3 = Zhrf3:gsub("q","Ꮕ")
Zhrf3 = Zhrf3:gsub("Q","Ꮕ")
Zhrf3 = Zhrf3:gsub("r","ᖇ")
Zhrf3 = Zhrf3:gsub("R","ᖇ")
Zhrf3 = Zhrf3:gsub("s","Ꮥ")
Zhrf3 = Zhrf3:gsub("S","Ꮥ")
Zhrf3 = Zhrf3:gsub("t","Ꮱ")
Zhrf3 = Zhrf3:gsub("T","Ꮱ")
Zhrf3 = Zhrf3:gsub("u","Ꮼ")
Zhrf3 = Zhrf3:gsub("U","Ꮼ")
Zhrf3 = Zhrf3:gsub("v","Ꮙ")
Zhrf3 = Zhrf3:gsub("V","Ꮙ")
Zhrf3 = Zhrf3:gsub("w","Ꮗ")
Zhrf3 = Zhrf3:gsub("W","Ꮗ")
Zhrf3 = Zhrf3:gsub("x","Ꮂ")
Zhrf3 = Zhrf3:gsub("X","Ꮂ")
Zhrf3 = Zhrf3:gsub("y","Ꮍ")
Zhrf3 = Zhrf3:gsub("Y","Ꮍ")
Zhrf3 = Zhrf3:gsub("z","ᔓ")
Zhrf3 = Zhrf3:gsub("Z","ᔓ")



local Zhrf4 = Text:gsub('ض','ضَٰـُـٰٓ')
Zhrf4 = Zhrf4:gsub('ص','صَٰـُـٰٓ')
Zhrf4 = Zhrf4:gsub('ث','ثَٰـُـٰٓ')
Zhrf4 = Zhrf4:gsub('ق','قَٰـُـٰٓ')
Zhrf4 = Zhrf4:gsub('ف','فَٰ͒ـُـٰٓ')
Zhrf4 = Zhrf4:gsub('غ','غَٰـُـٰٓ')
Zhrf4 = Zhrf4:gsub('ع','عَٰـُـٰٓ')
Zhrf4 = Zhrf4:gsub('خ','خَٰ̐ـُـٰٓ')
Zhrf4 = Zhrf4:gsub('ح','حَٰـُـٰٓ')
Zhrf4 = Zhrf4:gsub('ج','جَٰـُـٰٓ')
Zhrf4 = Zhrf4:gsub('ش','شَٰـُـٰٓ')
Zhrf4 = Zhrf4:gsub('س','سَٰـُـٰٓ')
Zhrf4 = Zhrf4:gsub('ي','يَٰـُـٰٓ')
Zhrf4 = Zhrf4:gsub('ب','بَٰـُـٰٓ')
Zhrf4 = Zhrf4:gsub('ل','لَٰـُـٰٓ')
Zhrf4 = Zhrf4:gsub('ا','آ')
Zhrf4 = Zhrf4:gsub('ت','تَٰـُـٰٓ')
Zhrf4 = Zhrf4:gsub('ن','نَٰـُـٰٓ')
Zhrf4 = Zhrf4:gsub('م','مَٰـُـٰٓ')
Zhrf4 = Zhrf4:gsub('ك','ڪَٰـُـٰٓ')
Zhrf4 = Zhrf4:gsub('ط','طَٰـُـٰٓ')
Zhrf4 = Zhrf4:gsub('ظ','ظَٰـُـٰٓ')
Zhrf4 = Zhrf4:gsub('ء','ء')
Zhrf4 = Zhrf4:gsub('ؤ','ؤ')
Zhrf4 = Zhrf4:gsub('ر','ر')
Zhrf4 = Zhrf4:gsub('ى','ى')
Zhrf4 = Zhrf4:gsub('ز','ز')
Zhrf4 = Zhrf4:gsub('و','ﯛ̲୭')
Zhrf4 = Zhrf4:gsub("ه", "ۿۿہ")
Zhrf4 = Zhrf4:gsub('a',"ᵃ")
Zhrf4 = Zhrf4:gsub('A',"ᵃ")
Zhrf4 = Zhrf4:gsub("b","ᵇ")
Zhrf4 = Zhrf4:gsub("B","ᵇ")
Zhrf4 = Zhrf4:gsub("c","ᶜ")
Zhrf4 = Zhrf4:gsub("C","ᶜ")
Zhrf4 = Zhrf4:gsub("d","ᵈ")
Zhrf4 = Zhrf4:gsub("D","ᵈ")
Zhrf4 = Zhrf4:gsub("e","ᵉ")
Zhrf4 = Zhrf4:gsub("E","ᵉ")
Zhrf4 = Zhrf4:gsub("f","ᶠ")
Zhrf4 = Zhrf4:gsub("F","ᶠ")
Zhrf4 = Zhrf4:gsub("g","ᵍ")
Zhrf4 = Zhrf4:gsub("G","ᵍ")
Zhrf4 = Zhrf4:gsub("h","ʰ")
Zhrf4 = Zhrf4:gsub("H","ʰ")
Zhrf4 = Zhrf4:gsub("i","ᶤ")
Zhrf4 = Zhrf4:gsub("I","ᶤ")
Zhrf4 = Zhrf4:gsub("j","ʲ")
Zhrf4 = Zhrf4:gsub("J","ʲ")
Zhrf4 = Zhrf4:gsub("k","ᵏ")
Zhrf4 = Zhrf4:gsub("K","ᵏ")
Zhrf4 = Zhrf4:gsub("l","ˡ")
Zhrf4 = Zhrf4:gsub("L","ˡ")
Zhrf4 = Zhrf4:gsub("m","ᵐ")
Zhrf4 = Zhrf4:gsub("M","ᵐ")
Zhrf4 = Zhrf4:gsub("n","ᶰ")
Zhrf4 = Zhrf4:gsub("N","ᶰ")
Zhrf4 = Zhrf4:gsub("o","ᵒ")
Zhrf4 = Zhrf4:gsub("O","ᵒ")
Zhrf4 = Zhrf4:gsub("p","ᵖ")
Zhrf4 = Zhrf4:gsub("P","ᵖ")
Zhrf4 = Zhrf4:gsub("q","ᵠ")
Zhrf4 = Zhrf4:gsub("Q","ᵠ")
Zhrf4 = Zhrf4:gsub("r","ʳ")
Zhrf4 = Zhrf4:gsub("R","ʳ")
Zhrf4 = Zhrf4:gsub("s","ˢ")
Zhrf4 = Zhrf4:gsub("S","ˢ")
Zhrf4 = Zhrf4:gsub("t","ᵗ")
Zhrf4 = Zhrf4:gsub("T","ᵗ")
Zhrf4 = Zhrf4:gsub("u","ᵘ")
Zhrf4 = Zhrf4:gsub("U","ᵘ")
Zhrf4 = Zhrf4:gsub("v","ᵛ")
Zhrf4 = Zhrf4:gsub("V","ᵛ")
Zhrf4 = Zhrf4:gsub("w","ʷ")
Zhrf4 = Zhrf4:gsub("W","ʷ")
Zhrf4 = Zhrf4:gsub("x","ˣ")
Zhrf4 = Zhrf4:gsub("X","ˣ")
Zhrf4 = Zhrf4:gsub("y","ʸ")
Zhrf4 = Zhrf4:gsub("Y","ʸ")
Zhrf4 = Zhrf4:gsub("z","ᶻ")
Zhrf4 = Zhrf4:gsub("Z","ᶻ")


local Zhrf5= Text:gsub('ض','ض')
Zhrf5= Zhrf5:gsub('ص','ص')
Zhrf5= Zhrf5:gsub('ث','ثہ')
Zhrf5= Zhrf5:gsub('ق','ق')
Zhrf5= Zhrf5:gsub('ف','فُہ')
Zhrf5= Zhrf5:gsub('غ','غہ')
Zhrf5= Zhrf5:gsub('ع','عہ')
Zhrf5= Zhrf5:gsub('ه','هٰہٰٖ')
Zhrf5= Zhrf5:gsub('خ','خہ')
Zhrf5= Zhrf5:gsub('ح','حہ')
Zhrf5= Zhrf5:gsub('ج','جہ')
Zhrf5= Zhrf5:gsub('د','د')
Zhrf5= Zhrf5:gsub('ذ','ذ')
Zhrf5= Zhrf5:gsub('ش','شہ')
Zhrf5= Zhrf5:gsub('س','سہ')
Zhrf5= Zhrf5:gsub('ي','يہ')
Zhrf5= Zhrf5:gsub('ب','بّ')
Zhrf5= Zhrf5:gsub('ل','لہ')
Zhrf5= Zhrf5:gsub('ا','ا')
Zhrf5= Zhrf5:gsub('ت','تہ')
Zhrf5= Zhrf5:gsub('ن','نٰہٰٖ')
Zhrf5= Zhrf5:gsub('م','مٰہٰٖ')
Zhrf5= Zhrf5:gsub('ك','كُہ')
Zhrf5= Zhrf5:gsub('ط','طہ')
Zhrf5= Zhrf5:gsub('ئ','ئ ْٰ')
Zhrf5= Zhrf5:gsub('ء','ء')
Zhrf5= Zhrf5:gsub('ؤ','ؤ')
Zhrf5= Zhrf5:gsub('ر','رَ')
Zhrf5= Zhrf5:gsub('لا','لہا')
Zhrf5= Zhrf5:gsub('ى','ىْ')
Zhrf5= Zhrf5:gsub('ة','ة')
Zhrf5= Zhrf5:gsub('و','و')
Zhrf5= Zhrf5:gsub('ز','ز')
Zhrf5= Zhrf5:gsub('ظ','ظۗہٰٰ')
Zhrf5= Zhrf5:gsub('q','Ꝙ')
Zhrf5= Zhrf5:gsub('Q','Ꝙ')
Zhrf5= Zhrf5:gsub('w','ᾧ')
Zhrf5= Zhrf5:gsub('W','ᾧ')
Zhrf5= Zhrf5:gsub('e','ἔ')
Zhrf5= Zhrf5:gsub('E','ἔ')
Zhrf5= Zhrf5:gsub('r','ʀ')
Zhrf5= Zhrf5:gsub('R','ʀ')
Zhrf5= Zhrf5:gsub('t','ҭ')
Zhrf5= Zhrf5:gsub('T','ҭ')
Zhrf5= Zhrf5:gsub('y','ẏ')
Zhrf5= Zhrf5:gsub('Y','ẏ')
Zhrf5= Zhrf5:gsub('u','ὗ')
Zhrf5= Zhrf5:gsub('i','ἷ')
Zhrf5= Zhrf5:gsub('o','ὄ')
Zhrf5= Zhrf5:gsub('p','ῥ')
Zhrf5= Zhrf5:gsub('a','ᾄ')
Zhrf5= Zhrf5:gsub('s','ṩ')
Zhrf5= Zhrf5:gsub('d','ḋ')
Zhrf5= Zhrf5:gsub('f','ғ')
Zhrf5= Zhrf5:gsub('g','ʛ')
Zhrf5= Zhrf5:gsub('h','ђ')
Zhrf5= Zhrf5:gsub('j','ʝ')
Zhrf5= Zhrf5:gsub('k','ќ')
Zhrf5= Zhrf5:gsub('U','ὗ')
Zhrf5= Zhrf5:gsub('I','ἷ')
Zhrf5= Zhrf5:gsub('O','ὄ')
Zhrf5= Zhrf5:gsub('P','ῥ')
Zhrf5= Zhrf5:gsub('A','ᾄ')
Zhrf5= Zhrf5:gsub('S','ṩ')
Zhrf5= Zhrf5:gsub('D','ḋ')
Zhrf5= Zhrf5:gsub('F','ғ')
Zhrf5= Zhrf5:gsub('G','ʛ')
Zhrf5= Zhrf5:gsub('H','ђ')
Zhrf5= Zhrf5:gsub('J','ʝ')
Zhrf5= Zhrf5:gsub('K','ќ')
Zhrf5= Zhrf5:gsub('L','ł')
Zhrf5= Zhrf5:gsub('l','ł')
Zhrf5= Zhrf5:gsub('z','ẓ')
Zhrf5= Zhrf5:gsub('Z','ẓ')
Zhrf5= Zhrf5:gsub('x','ẋ')
Zhrf5= Zhrf5:gsub('X','ẋ')
Zhrf5= Zhrf5:gsub('c','ƈ')
Zhrf5= Zhrf5:gsub('C','ƈ')
Zhrf5= Zhrf5:gsub('v','v')
Zhrf5= Zhrf5:gsub('V','v')
Zhrf5= Zhrf5:gsub('b','в')
Zhrf5= Zhrf5:gsub('B','в')
Zhrf5= Zhrf5:gsub('n','ᾗ')
Zhrf5= Zhrf5:gsub('N','ᾗ')
Zhrf5= Zhrf5:gsub('m','м')
Zhrf5= Zhrf5:gsub('M','м')



local Zhrf6= Text:gsub('ض','ضـٰ̲ـہۜہٰٰ')
Zhrf6= Zhrf6:gsub('ص','صـٰ̲ـہۛہٰٰ')
Zhrf6= Zhrf6:gsub('ث','ثـٰ̲ـہہٰٰ')
Zhrf6= Zhrf6:gsub('ق','قـٰ̲ـہྀ̲ہٰٰ')
Zhrf6= Zhrf6:gsub('ف','فـٰ̲ـہ͒ہٰٰ')
Zhrf6= Zhrf6:gsub('غ','غـٰ̲ـہہٰٰ')
Zhrf6= Zhrf6:gsub('ع','غـٰ̲ـہہٰٰ')
Zhrf6= Zhrf6:gsub('ه','هٰہٰٖ')
Zhrf6= Zhrf6:gsub('خ','خـٰ̲ـہٰ̐ہ ')
Zhrf6= Zhrf6:gsub('ح','حـٰ̲ـہہٰٰ')
Zhrf6= Zhrf6:gsub('ج','جـٰ̲ـہْۧ')
Zhrf6= Zhrf6:gsub('د','دٰ')
Zhrf6= Zhrf6:gsub('ذ','ذِٰ')
Zhrf6= Zhrf6:gsub('ش','شـٰ̲ـہِٰہٰٰ')
Zhrf6= Zhrf6:gsub('س','شـٰ̲ـہِٰہٰٰ')
Zhrf6= Zhrf6:gsub('ي','شـٰ̲ـہِٰہٰٰ')
Zhrf6= Zhrf6:gsub('ب','بـٰ̲ـہّہ')
Zhrf6= Zhrf6:gsub('ل','لـٰ̲ـہ')
Zhrf6= Zhrf6:gsub('ا','آ')
Zhrf6= Zhrf6:gsub('ت','تـٰ̲ـہَہَٰ')
Zhrf6= Zhrf6:gsub('ن','نـٰ̲ـہَِہ')
Zhrf6= Zhrf6:gsub('م','مـٰ̲ـہٰ̲ہ')
Zhrf6= Zhrf6:gsub('ك','ڪٰྀہٰٰ')
Zhrf6= Zhrf6:gsub('ط','طـٰ̲ـہۨہٰٰ')
Zhrf6= Zhrf6:gsub('ئ','ئ ْٰ')
Zhrf6= Zhrf6:gsub('ء','ء')
Zhrf6= Zhrf6:gsub('ؤ','ؤ')
Zhrf6= Zhrf6:gsub('ر','رَ')
Zhrf6= Zhrf6:gsub('لا','لہا')
Zhrf6= Zhrf6:gsub('ى','ىْ')
Zhrf6= Zhrf6:gsub('ة','ة')
Zhrf6= Zhrf6:gsub('و','وِٰ')
Zhrf6= Zhrf6:gsub('ز','زَٰ')
Zhrf6= Zhrf6:gsub('ظ','ظۗہٰٰ')
Zhrf6= Zhrf6:gsub('q','Ꝙ')
Zhrf6= Zhrf6:gsub('Q','Ꝙ')
Zhrf6= Zhrf6:gsub('w','Ɯ')
Zhrf6= Zhrf6:gsub('W','Ɯ')
Zhrf6= Zhrf6:gsub('e','Є')
Zhrf6= Zhrf6:gsub('E','Є')
Zhrf6= Zhrf6:gsub('r','Ʀ')
Zhrf6= Zhrf6:gsub('R','Ʀ')
Zhrf6= Zhrf6:gsub('t','Ƭ')
Zhrf6= Zhrf6:gsub('T','Ƭ')
Zhrf6= Zhrf6:gsub('y','Ƴ')
Zhrf6= Zhrf6:gsub('Y','Ƴ')
Zhrf6= Zhrf6:gsub('u','Ʋ')
Zhrf6= Zhrf6:gsub('i','Ɩ')
Zhrf6= Zhrf6:gsub('o','Ơ')
Zhrf6= Zhrf6:gsub('p','Ƥ')
Zhrf6= Zhrf6:gsub('a','ƛ')
Zhrf6= Zhrf6:gsub('s','Ƨ')
Zhrf6= Zhrf6:gsub('d','Ɗ')
Zhrf6= Zhrf6:gsub('f','Ƒ')
Zhrf6= Zhrf6:gsub('g','Ɠ')
Zhrf6= Zhrf6:gsub('h','Ӈ')
Zhrf6= Zhrf6:gsub('j','ʆ')
Zhrf6= Zhrf6:gsub('k','Ƙ')
Zhrf6= Zhrf6:gsub('U','Ʋ')
Zhrf6= Zhrf6:gsub('I','Ɩ')
Zhrf6= Zhrf6:gsub('O','Ơ')
Zhrf6= Zhrf6:gsub('P','Ƥ')
Zhrf6= Zhrf6:gsub('A','ƛ')
Zhrf6= Zhrf6:gsub('S','Ƨ')
Zhrf6= Zhrf6:gsub('D','ḋ')
Zhrf6= Zhrf6:gsub('F','ғ')
Zhrf6= Zhrf6:gsub('G','ʛ')
Zhrf6= Zhrf6:gsub('H','ђ')
Zhrf6= Zhrf6:gsub('J','ʝ')
Zhrf6= Zhrf6:gsub('K','ќ')
Zhrf6= Zhrf6:gsub('L','Լ')
Zhrf6= Zhrf6:gsub('l','Լ')
Zhrf6= Zhrf6:gsub('z','Ȥ')
Zhrf6= Zhrf6:gsub('Z','Ȥ')
Zhrf6= Zhrf6:gsub('x','Ҳ')
Zhrf6= Zhrf6:gsub('X','Ҳ')
Zhrf6= Zhrf6:gsub('c','Ƈ')
Zhrf6= Zhrf6:gsub('C','Ƈ')
Zhrf6= Zhrf6:gsub('v','Ɣ')
Zhrf6= Zhrf6:gsub('V','Ɣ')
Zhrf6= Zhrf6:gsub('b','Ɓ')
Zhrf6= Zhrf6:gsub('B','Ɓ')
Zhrf6= Zhrf6:gsub('n','Ɲ')
Zhrf6= Zhrf6:gsub('N','Ɲ')
Zhrf6= Zhrf6:gsub('m','M')
Zhrf6= Zhrf6:gsub('M','M')



local Zhrf7= Text:gsub('ض','ضۜہٰٰ')
Zhrf7= Zhrf7:gsub('ص','ضۜہٰٰ')
Zhrf7= Zhrf7:gsub('ث','ثہٰٰ')
Zhrf7= Zhrf7:gsub('ق','قྀ̲ہٰٰ')
Zhrf7= Zhrf7:gsub('ف','ف͒ہٰٰ')
Zhrf7= Zhrf7:gsub('غ','غہٰٰ')
Zhrf7= Zhrf7:gsub('ع','عہٰٰ')
Zhrf7= Zhrf7:gsub('ه','هٰہٰٖ')
Zhrf7= Zhrf7:gsub('خ','خٰ̐ہ ')
Zhrf7= Zhrf7:gsub('ح','حہٰٰ')
Zhrf7= Zhrf7:gsub('ج','جـٰ̲ـہْۧ')
Zhrf7= Zhrf7:gsub('د','دٰ')
Zhrf7= Zhrf7:gsub('ذ','ذِٰ')
Zhrf7= Zhrf7:gsub('ش','شِٰہٰٰ')
Zhrf7= Zhrf7:gsub('س','سٰٓ')
Zhrf7= Zhrf7:gsub('ي','يِٰہ')
Zhrf7= Zhrf7:gsub('ب','بّہ')
Zhrf7= Zhrf7:gsub('ل','لـٰ̲ـہ')
Zhrf7= Zhrf7:gsub('ا','آ')
Zhrf7= Zhrf7:gsub('ت','تَہَٰ')
Zhrf7= Zhrf7:gsub('ن','نَِہ')
Zhrf7= Zhrf7:gsub('م','مٰ̲ہ')
Zhrf7= Zhrf7:gsub('ك','ڪٰྀہٰٰ')
Zhrf7= Zhrf7:gsub('ط','طۨہٰٰ')
Zhrf7= Zhrf7:gsub('ئ','ئ ْٰ')
Zhrf7= Zhrf7:gsub('ء','ء')
Zhrf7= Zhrf7:gsub('ؤ','ؤ')
Zhrf7= Zhrf7:gsub('ر','رَ')
Zhrf7= Zhrf7:gsub('لا','لہا')
Zhrf7= Zhrf7:gsub('ى','ىْ')
Zhrf7= Zhrf7:gsub('ة','ة')
Zhrf7= Zhrf7:gsub('و','وِٰ')
Zhrf7= Zhrf7:gsub('ز','زَٰ')
Zhrf7= Zhrf7:gsub('ظ','ظۗہٰٰ')
Zhrf7= Zhrf7:gsub('q','ℚ')
Zhrf7= Zhrf7:gsub('Q','ℚ')
Zhrf7= Zhrf7:gsub('w','𝕎')
Zhrf7= Zhrf7:gsub('W','𝕎')
Zhrf7= Zhrf7:gsub('e','𝔼')
Zhrf7= Zhrf7:gsub('E','𝔼')
Zhrf7= Zhrf7:gsub('r','ℝ')
Zhrf7= Zhrf7:gsub('R','ℝ')
Zhrf7= Zhrf7:gsub('t','𝕋')
Zhrf7= Zhrf7:gsub('T','𝕋')
Zhrf7= Zhrf7:gsub('y','𝕐')
Zhrf7= Zhrf7:gsub('Y','𝕐')
Zhrf7= Zhrf7:gsub('u','𝕌')
Zhrf7= Zhrf7:gsub('i','𝕀')
Zhrf7= Zhrf7:gsub('o','𝕆')
Zhrf7= Zhrf7:gsub('p','ℙ')
Zhrf7= Zhrf7:gsub('a','𝔸')
Zhrf7= Zhrf7:gsub('s','𝕊')
Zhrf7= Zhrf7:gsub('d','𝔻')
Zhrf7= Zhrf7:gsub('f','𝔽')
Zhrf7= Zhrf7:gsub('g','𝔾')
Zhrf7= Zhrf7:gsub('h','ℍ')
Zhrf7= Zhrf7:gsub('j','𝕁')
Zhrf7= Zhrf7:gsub('k','𝕂')
Zhrf7= Zhrf7:gsub('U','𝕌')
Zhrf7= Zhrf7:gsub('I','𝕀')
Zhrf7= Zhrf7:gsub('O','𝕆')
Zhrf7= Zhrf7:gsub('P','ℙ')
Zhrf7= Zhrf7:gsub('A','𝔸')
Zhrf7= Zhrf7:gsub('S','𝕊')
Zhrf7= Zhrf7:gsub('D','𝔻')
Zhrf7= Zhrf7:gsub('F','𝔽')
Zhrf7= Zhrf7:gsub('G','𝔾')
Zhrf7= Zhrf7:gsub('H','ℍ')
Zhrf7= Zhrf7:gsub('J','𝕁')
Zhrf7= Zhrf7:gsub('K','𝕂')
Zhrf7= Zhrf7:gsub('L','𝕃')
Zhrf7= Zhrf7:gsub('l','𝕃')
Zhrf7= Zhrf7:gsub('z','ℤ')
Zhrf7= Zhrf7:gsub('Z','ℤ')
Zhrf7= Zhrf7:gsub('x','𝕏')
Zhrf7= Zhrf7:gsub('X','𝕏')
Zhrf7= Zhrf7:gsub('c','ℂ')
Zhrf7= Zhrf7:gsub('C','ℂ')
Zhrf7= Zhrf7:gsub('v','𝕍')
Zhrf7= Zhrf7:gsub('V','𝕍')
Zhrf7= Zhrf7:gsub('b','𝔹')
Zhrf7= Zhrf7:gsub('B','𝔹')
Zhrf7= Zhrf7:gsub('n','ℕ')
Zhrf7= Zhrf7:gsub('N','ℕ')
Zhrf7= Zhrf7:gsub('m','𝕄')
Zhrf7= Zhrf7:gsub('M','𝕄')



local Zhrf8= Text:gsub('ض','ضَ')
Zhrf8= Zhrf8:gsub('ص','صً')
Zhrf8= Zhrf8:gsub('ث','ثَ')
Zhrf8= Zhrf8:gsub('ق','قُ')
Zhrf8= Zhrf8:gsub('ف','فّ')
Zhrf8= Zhrf8:gsub('غ','غِ')
Zhrf8= Zhrf8:gsub('ع','عُ')
Zhrf8= Zhrf8:gsub('ه','ﮭ')
Zhrf8= Zhrf8:gsub('خ','خِ')
Zhrf8= Zhrf8:gsub('ح','حٌ')
Zhrf8= Zhrf8:gsub('ج','جُ')
Zhrf8= Zhrf8:gsub('د','دِ')
Zhrf8= Zhrf8:gsub('ذ','ذَ')
Zhrf8= Zhrf8:gsub('ش','شِ')
Zhrf8= Zhrf8:gsub('س','سً')
Zhrf8= Zhrf8:gsub('ي','يْ')
Zhrf8= Zhrf8:gsub('ب','بّ')
Zhrf8= Zhrf8:gsub('ل','لَ')
Zhrf8= Zhrf8:gsub('ا','أُ')
Zhrf8= Zhrf8:gsub('ت','تٌ')
Zhrf8= Zhrf8:gsub('ن','نً')
Zhrf8= Zhrf8:gsub('م','مِ')
Zhrf8= Zhrf8:gsub('ك','ڳّ')
Zhrf8= Zhrf8:gsub('ط','طٌ')
Zhrf8= Zhrf8:gsub('ئ','ئ')
Zhrf8= Zhrf8:gsub('ء','ء')
Zhrf8= Zhrf8:gsub('ؤ','ؤ')
Zhrf8= Zhrf8:gsub('ر','رٌ')
Zhrf8= Zhrf8:gsub('لا','لٌأً')
Zhrf8= Zhrf8:gsub('ى','ى')
Zhrf8= Zhrf8:gsub('ة','ةَ')
Zhrf8= Zhrf8:gsub('و','وِ')
Zhrf8= Zhrf8:gsub('ز','زُ')
Zhrf8= Zhrf8:gsub('ظ','ظ')
Zhrf8= Zhrf8:gsub('q','ƍ')
Zhrf8= Zhrf8:gsub('Q','ƍ')
Zhrf8= Zhrf8:gsub('w','w')
Zhrf8= Zhrf8:gsub('W','w')
Zhrf8= Zhrf8:gsub('e','È')
Zhrf8= Zhrf8:gsub('E','È')
Zhrf8= Zhrf8:gsub('r','r')
Zhrf8= Zhrf8:gsub('R','r')
Zhrf8= Zhrf8:gsub('t','⊥')
Zhrf8= Zhrf8:gsub('T','⊥')
Zhrf8= Zhrf8:gsub('y','ý')
Zhrf8= Zhrf8:gsub('Y','ý')
Zhrf8= Zhrf8:gsub('u','µ')
Zhrf8= Zhrf8:gsub('U','µ')
Zhrf8= Zhrf8:gsub('i','Î')
Zhrf8= Zhrf8:gsub('I','Î')
Zhrf8= Zhrf8:gsub('o','◊')
Zhrf8= Zhrf8:gsub('O','◊')
Zhrf8= Zhrf8:gsub('p','Ƿ')
Zhrf8= Zhrf8:gsub('P','Ƿ')
Zhrf8= Zhrf8:gsub('a','ª')
Zhrf8= Zhrf8:gsub('A','ª')
Zhrf8= Zhrf8:gsub('s','S')
Zhrf8= Zhrf8:gsub('S','S')
Zhrf8= Zhrf8:gsub('d','Þ')
Zhrf8= Zhrf8:gsub('D','Þ')
Zhrf8= Zhrf8:gsub('f','F')
Zhrf8= Zhrf8:gsub('F','F')
Zhrf8= Zhrf8:gsub('g','૬')
Zhrf8= Zhrf8:gsub('G','૬')
Zhrf8= Zhrf8:gsub('h','ɧ')
Zhrf8= Zhrf8:gsub('H','ɧ')
Zhrf8= Zhrf8:gsub('j','j')
Zhrf8= Zhrf8:gsub('J','j')
Zhrf8= Zhrf8:gsub('L','Ļ')
Zhrf8= Zhrf8:gsub('l','Ļ')
Zhrf8= Zhrf8:gsub('z','z')
Zhrf8= Zhrf8:gsub('Z','z')
Zhrf8= Zhrf8:gsub('x','×')
Zhrf8= Zhrf8:gsub('X','×')
Zhrf8= Zhrf8:gsub('c','¢')
Zhrf8= Zhrf8:gsub('C','¢')
Zhrf8= Zhrf8:gsub('v','√')
Zhrf8= Zhrf8:gsub('V','√')
Zhrf8= Zhrf8:gsub('b','b')
Zhrf8= Zhrf8:gsub('B','b')
Zhrf8= Zhrf8:gsub('n','η')
Zhrf8= Zhrf8:gsub('N','η')
Zhrf8= Zhrf8:gsub('m','м')
Zhrf8= Zhrf8:gsub('M','м')



local Zhrf9= Text:gsub('ض','ﺿ̭͠')
Zhrf9= Zhrf9:gsub('ص','ﺻ͡')
Zhrf9= Zhrf9:gsub('ث','ﺜ̲')
Zhrf9= Zhrf9:gsub('ق','ﭰ')
Zhrf9= Zhrf9:gsub('ف','ﻓ̲')
Zhrf9= Zhrf9:gsub('غ','ﻏ̲')
Zhrf9= Zhrf9:gsub('ع','ﻌ̲')
Zhrf9= Zhrf9:gsub('ه','ﮬ̲̌')
Zhrf9= Zhrf9:gsub('خ','خٌ')
Zhrf9= Zhrf9:gsub('ح','ﺣ̅')
Zhrf9= Zhrf9:gsub('ج','جُ')
Zhrf9= Zhrf9:gsub('د','ډ̝')
Zhrf9= Zhrf9:gsub('ذ','ذً')
Zhrf9= Zhrf9:gsub('ش','ﺷ̲')
Zhrf9= Zhrf9:gsub('س','ﺳ̉')
Zhrf9= Zhrf9:gsub('ي','ﯾ̃̐')
Zhrf9= Zhrf9:gsub('ب','ﺑ̲')
Zhrf9= Zhrf9:gsub('ل','ا̄ﻟ')
Zhrf9= Zhrf9:gsub('ا','ﺈ̃')
Zhrf9= Zhrf9:gsub('ت','ټُ')
Zhrf9= Zhrf9:gsub('ن','ﻧ̲')
Zhrf9= Zhrf9:gsub('م','ﻣ̲̉')
Zhrf9= Zhrf9:gsub('ك','گ')
Zhrf9= Zhrf9:gsub('ط','ﻁ̲')
Zhrf9= Zhrf9:gsub('ئ',' ْٰئ')
Zhrf9= Zhrf9:gsub('ء','ء')
Zhrf9= Zhrf9:gsub('ؤ','ؤ')
Zhrf9= Zhrf9:gsub('ر','ہڕ')
Zhrf9= Zhrf9:gsub('لا','ﻟ̲ﺂ̲')
Zhrf9= Zhrf9:gsub('ى','ى')
Zhrf9= Zhrf9:gsub('ة','ة')
Zhrf9= Zhrf9:gsub('و','ۇۈۉ')
Zhrf9= Zhrf9:gsub('ز','زُ')
Zhrf9= Zhrf9:gsub('ظ','ﻇ̲')
Zhrf9= Zhrf9:gsub('q','Ⴓ')
Zhrf9= Zhrf9:gsub('Q','Ⴓ')
Zhrf9= Zhrf9:gsub('w','Ш')
Zhrf9= Zhrf9:gsub('W','Ш')
Zhrf9= Zhrf9:gsub('e','Σ')
Zhrf9= Zhrf9:gsub('E','Σ')
Zhrf9= Zhrf9:gsub('r','Γ')
Zhrf9= Zhrf9:gsub('R','Γ')
Zhrf9= Zhrf9:gsub('t','Ƭ')
Zhrf9= Zhrf9:gsub('T','Ƭ')
Zhrf9= Zhrf9:gsub('y','Ψ')
Zhrf9= Zhrf9:gsub('Y','Ψ')
Zhrf9= Zhrf9:gsub('u','Ʊ')
Zhrf9= Zhrf9:gsub('U','Ʊ')
Zhrf9= Zhrf9:gsub('i','I')
Zhrf9= Zhrf9:gsub('I','I')
Zhrf9= Zhrf9:gsub('o','Θ')
Zhrf9= Zhrf9:gsub('O','Θ')
Zhrf9= Zhrf9:gsub('p','Ƥ')
Zhrf9= Zhrf9:gsub('P','Ƥ')
Zhrf9= Zhrf9:gsub('a','Δ')
Zhrf9= Zhrf9:gsub('A','Δ')
Zhrf9= Zhrf9:gsub('s','Ѕ')
Zhrf9= Zhrf9:gsub('S','Ѕ')
Zhrf9= Zhrf9:gsub('d','D')
Zhrf9= Zhrf9:gsub('D','D')
Zhrf9= Zhrf9:gsub('f','F')
Zhrf9= Zhrf9:gsub('F','F')
Zhrf9= Zhrf9:gsub('g','G')
Zhrf9= Zhrf9:gsub('G','G')
Zhrf9= Zhrf9:gsub('h','H')
Zhrf9= Zhrf9:gsub('H','H')
Zhrf9= Zhrf9:gsub('j','J')
Zhrf9= Zhrf9:gsub('J','J')
Zhrf9= Zhrf9:gsub('L','L')
Zhrf9= Zhrf9:gsub('l','L')
Zhrf9= Zhrf9:gsub('z','Z')
Zhrf9= Zhrf9:gsub('Z','Z')
Zhrf9= Zhrf9:gsub('x','Ж')
Zhrf9= Zhrf9:gsub('X','Ж')
Zhrf9= Zhrf9:gsub('c','C')
Zhrf9= Zhrf9:gsub('C','C')
Zhrf9= Zhrf9:gsub('v','Ʋ')
Zhrf9= Zhrf9:gsub('V','Ʋ')
Zhrf9= Zhrf9:gsub('b','Ɓ')
Zhrf9= Zhrf9:gsub('B','Ɓ')
Zhrf9= Zhrf9:gsub('n','∏')
Zhrf9= Zhrf9:gsub('N','∏')
Zhrf9= Zhrf9:gsub('m','Μ')
Zhrf9= Zhrf9:gsub('M','Μ')



local Zhrf10= Text:gsub('ض','ﺿ')
Zhrf10= Zhrf10:gsub('ص','ﺻ')
Zhrf10= Zhrf10:gsub('ث','ﭥ')
Zhrf10= Zhrf10:gsub('ق','ﻗ̮ـ̃')
Zhrf10= Zhrf10:gsub('ف','ﭬ')
Zhrf10= Zhrf10:gsub('غ','ﻏ̣̐')
Zhrf10= Zhrf10:gsub('ع','ﻋ')
Zhrf10= Zhrf10:gsub('ه','ھَہّ')
Zhrf10= Zhrf10:gsub('خ','ﺧ')
Zhrf10= Zhrf10:gsub('ح','פ')
Zhrf10= Zhrf10:gsub('ج','ﭴ')
Zhrf10= Zhrf10:gsub('د','ﮃ')
Zhrf10= Zhrf10:gsub('ذ','ذ')
Zhrf10= Zhrf10:gsub('ش','ﺷ')
Zhrf10= Zhrf10:gsub('س','ﺳ')
Zhrf10= Zhrf10:gsub('ي','ﯾ')
Zhrf10= Zhrf10:gsub('ب','ﺑ')
Zhrf10= Zhrf10:gsub('ل','ﻟ')
Zhrf10= Zhrf10:gsub('ا','ﺂ')
Zhrf10= Zhrf10:gsub('ت','ﭠ')
Zhrf10= Zhrf10:gsub('ن','ﻧ')
Zhrf10= Zhrf10:gsub('م','ﻣ̝̚')
Zhrf10= Zhrf10:gsub('ك','گـ')
Zhrf10= Zhrf10:gsub('ط','ﻁْ')
Zhrf10= Zhrf10:gsub('ئ','ٰئـ')
Zhrf10= Zhrf10:gsub('ء','ء')
Zhrf10= Zhrf10:gsub('ؤ','ﯗ')
Zhrf10= Zhrf10:gsub('ر','ړُ')
Zhrf10= Zhrf10:gsub('لا','ﻟآ')
Zhrf10= Zhrf10:gsub('ى','ـﮯ')
Zhrf10= Zhrf10:gsub('ة','ة')
Zhrf10= Zhrf10:gsub('و','ۆ')
Zhrf10= Zhrf10:gsub('ز','ژ')
Zhrf10= Zhrf10:gsub('ظ','ﻅ')
Zhrf10= Zhrf10:gsub('q','๑')
Zhrf10= Zhrf10:gsub('Q','๑')
Zhrf10= Zhrf10:gsub('w','ຟ')
Zhrf10= Zhrf10:gsub('W','ຟ')
Zhrf10= Zhrf10:gsub('e','ē')
Zhrf10= Zhrf10:gsub('E','ē')
Zhrf10= Zhrf10:gsub('r','r')
Zhrf10= Zhrf10:gsub('R','r')
Zhrf10= Zhrf10:gsub('t','t')
Zhrf10= Zhrf10:gsub('T','t')
Zhrf10= Zhrf10:gsub('y','ฯ')
Zhrf10= Zhrf10:gsub('Y','ฯ')
Zhrf10= Zhrf10:gsub('u','น')
Zhrf10= Zhrf10:gsub('U','น')
Zhrf10= Zhrf10:gsub('i','i')
Zhrf10= Zhrf10:gsub('I','i')
Zhrf10= Zhrf10:gsub('o','໐')
Zhrf10= Zhrf10:gsub('O','໐')
Zhrf10= Zhrf10:gsub('p','p')
Zhrf10= Zhrf10:gsub('P','p')
Zhrf10= Zhrf10:gsub('a','ค')
Zhrf10= Zhrf10:gsub('A','ค')
Zhrf10= Zhrf10:gsub('s','Ş')
Zhrf10= Zhrf10:gsub('S','Ş')
Zhrf10= Zhrf10:gsub('d','໓')
Zhrf10= Zhrf10:gsub('D','໓')
Zhrf10= Zhrf10:gsub('f','f')
Zhrf10= Zhrf10:gsub('F','f')
Zhrf10= Zhrf10:gsub('g','ງ')
Zhrf10= Zhrf10:gsub('G','ງ')
Zhrf10= Zhrf10:gsub('h','h')
Zhrf10= Zhrf10:gsub('H','h')
Zhrf10= Zhrf10:gsub('j','ว')
Zhrf10= Zhrf10:gsub('J','ว')
Zhrf10= Zhrf10:gsub('k','k')
Zhrf10= Zhrf10:gsub('K','k')
Zhrf10= Zhrf10:gsub('L','l')
Zhrf10= Zhrf10:gsub('l','l')
Zhrf10= Zhrf10:gsub('z','ຊ')
Zhrf10= Zhrf10:gsub('Z','ຊ')
Zhrf10= Zhrf10:gsub('x','x')
Zhrf10= Zhrf10:gsub('X','x')
Zhrf10= Zhrf10:gsub('c','¢')
Zhrf10= Zhrf10:gsub('C','¢')
Zhrf10= Zhrf10:gsub('v','ง')
Zhrf10= Zhrf10:gsub('V','ง')
Zhrf10= Zhrf10:gsub('b','๖')
Zhrf10= Zhrf10:gsub('B','๖')
Zhrf10= Zhrf10:gsub('n','ຖ')
Zhrf10= Zhrf10:gsub('N','ຖ')
Zhrf10= Zhrf10:gsub('m','๓')
Zhrf10= Zhrf10:gsub('M','๓')



local Zhrf11= Text:gsub('ض','ض');
Zhrf11= Zhrf11:gsub('ص','صہٰ')
Zhrf11= Zhrf11:gsub('ث','ثہٰـ')
Zhrf11= Zhrf11:gsub('ق','قہٰ')
Zhrf11= Zhrf11:gsub('ف','فہٰ')
Zhrf11= Zhrf11:gsub('غ','غـْ')
Zhrf11= Zhrf11:gsub('ع','ع')
Zhrf11= Zhrf11:gsub('ه','هٰہٰٖ')
Zhrf11= Zhrf11:gsub('خ','خخَـ')
Zhrf11= Zhrf11:gsub('ح','حہٰ')
Zhrf11= Zhrf11:gsub('ج','ججہٰ')
Zhrf11= Zhrf11:gsub('د','دَ')
Zhrf11= Zhrf11:gsub('ذ','ذّ')
Zhrf11= Zhrf11:gsub('ش','ششہٰ')
Zhrf11= Zhrf11:gsub('س','سہٰ')
Zhrf11= Zhrf11:gsub('ي','يٰ')
Zhrf11= Zhrf11:gsub('ب','بٰٰ')
Zhrf11= Zhrf11:gsub('ل','لہٰ')
Zhrf11= Zhrf11:gsub('ا','آ')
Zhrf11= Zhrf11:gsub('ت','تہٰ')
Zhrf11= Zhrf11:gsub('ن','نہٰ')
Zhrf11= Zhrf11:gsub('م','مہٰ')
Zhrf11= Zhrf11:gsub('ك','ككہٰ')
Zhrf11= Zhrf11:gsub('ط','طہٰ')
Zhrf11= Zhrf11:gsub('ئ',' ْئٰ')
Zhrf11= Zhrf11:gsub('ء','ء')
Zhrf11= Zhrf11:gsub('ؤ','ؤؤَ')
Zhrf11= Zhrf11:gsub('ر','رَ')
Zhrf11= Zhrf11:gsub('لا','لہٰا')
Zhrf11= Zhrf11:gsub('ى','ىہٰ')
Zhrf11= Zhrf11:gsub('ة','ة')
Zhrf11= Zhrf11:gsub('و','ہٰو')
Zhrf11= Zhrf11:gsub('ز','ز')
Zhrf11= Zhrf11:gsub('ظ','ظہٰ')
Zhrf11= Zhrf11:gsub('q','զ')
Zhrf11= Zhrf11:gsub('Q','զ')
Zhrf11= Zhrf11:gsub('w','ա')
Zhrf11= Zhrf11:gsub('W','ա')
Zhrf11= Zhrf11:gsub('e','ɛ')
Zhrf11= Zhrf11:gsub('E','ɛ')
Zhrf11= Zhrf11:gsub('r','ʀ')
Zhrf11= Zhrf11:gsub('R','ʀ')
Zhrf11= Zhrf11:gsub('t','ȶ')
Zhrf11= Zhrf11:gsub('T','ȶ')
Zhrf11= Zhrf11:gsub('y','ʏ')
Zhrf11= Zhrf11:gsub('Y','ʏ')
Zhrf11= Zhrf11:gsub('u','ʊ')
Zhrf11= Zhrf11:gsub('U','ʊ')
Zhrf11= Zhrf11:gsub('i','ɨ')
Zhrf11= Zhrf11:gsub('I','ɨ')
Zhrf11= Zhrf11:gsub('o','օ')
Zhrf11= Zhrf11:gsub('O','օ')
Zhrf11= Zhrf11:gsub('p','ք')
Zhrf11= Zhrf11:gsub('P','ք')
Zhrf11= Zhrf11:gsub('a','ǟ')
Zhrf11= Zhrf11:gsub('A','ǟ')
Zhrf11= Zhrf11:gsub('s','ֆ')
Zhrf11= Zhrf11:gsub('S','ֆ')
Zhrf11= Zhrf11:gsub('d','ɖ')
Zhrf11= Zhrf11:gsub('D','ɖ')
Zhrf11= Zhrf11:gsub('f','ʄ')
Zhrf11= Zhrf11:gsub('F','ʄ')
Zhrf11= Zhrf11:gsub('g','ɢ')
Zhrf11= Zhrf11:gsub('G','ɢ')
Zhrf11= Zhrf11:gsub('h','ɦ')
Zhrf11= Zhrf11:gsub('H','ɦ')
Zhrf11= Zhrf11:gsub('j','ʝ')
Zhrf11= Zhrf11:gsub('J','ʝ')
Zhrf11= Zhrf11:gsub('k','ӄ')
Zhrf11= Zhrf11:gsub('K','ӄ')
Zhrf11= Zhrf11:gsub('L','ʟ')
Zhrf11= Zhrf11:gsub('l','ʟ')
Zhrf11= Zhrf11:gsub('z','ʐ')
Zhrf11= Zhrf11:gsub('Z','ʐ')
Zhrf11= Zhrf11:gsub('x','Ӽ')
Zhrf11= Zhrf11:gsub('X','Ӽ')
Zhrf11= Zhrf11:gsub('c','ƈ')
Zhrf11= Zhrf11:gsub('C','ƈ')
Zhrf11= Zhrf11:gsub('v','ʋ')
Zhrf11= Zhrf11:gsub('V','ʋ')
Zhrf11= Zhrf11:gsub('b','ɮ')
Zhrf11= Zhrf11:gsub('B','ɮ')
Zhrf11= Zhrf11:gsub('n','ռ')
Zhrf11= Zhrf11:gsub('N','ռ')
Zhrf11= Zhrf11:gsub('m','ʍ')
Zhrf11= Zhrf11:gsub('M','ʍ')



local Zhrf12= Text:gsub('ض','ض')
Zhrf12= Zhrf12:gsub('ص','ص')
Zhrf12= Zhrf12:gsub('ث','ث')
Zhrf12= Zhrf12:gsub('ق','قٌ')
Zhrf12= Zhrf12:gsub('ف','فُ')
Zhrf12= Zhrf12:gsub('غ','غ')
Zhrf12= Zhrf12:gsub('ع','عٍ')
Zhrf12= Zhrf12:gsub('ه','هـ')
Zhrf12= Zhrf12:gsub('خ','خـ')
Zhrf12= Zhrf12:gsub('ح','حٍ')
Zhrf12= Zhrf12:gsub('ج','جٍ')
Zhrf12= Zhrf12:gsub('د','دِ')
Zhrf12= Zhrf12:gsub('ذ','ذَ')
Zhrf12= Zhrf12:gsub('ش','شُ')
Zhrf12= Zhrf12:gsub('س','س')
Zhrf12= Zhrf12:gsub('ي','ي')
Zhrf12= Zhrf12:gsub('ب','بَ')
Zhrf12= Zhrf12:gsub('ل','لُِ')
Zhrf12= Zhrf12:gsub('ا','آ')
Zhrf12= Zhrf12:gsub('ت','ت')
Zhrf12= Zhrf12:gsub('ن','ن')
Zhrf12= Zhrf12:gsub('م','م')
Zhrf12= Zhrf12:gsub('ك','ڪ')
Zhrf12= Zhrf12:gsub('ط','طُ')
Zhrf12= Zhrf12:gsub('ئ','ئ ْٰ')
Zhrf12= Zhrf12:gsub('ء','ء')
Zhrf12= Zhrf12:gsub('ؤ','ؤ')
Zhrf12= Zhrf12:gsub('ر','ر')
Zhrf12= Zhrf12:gsub('لا','لُِآ')
Zhrf12= Zhrf12:gsub('ى','ىْ')
Zhrf12= Zhrf12:gsub('ة','ة')
Zhrf12= Zhrf12:gsub('و','وو')
Zhrf12= Zhrf12:gsub('ز','ز')
Zhrf12= Zhrf12:gsub('ظ','ظهُ')
Zhrf12= Zhrf12:gsub('q','Q')
Zhrf12= Zhrf12:gsub('Q','Q')
Zhrf12= Zhrf12:gsub('w','Ẃ')
Zhrf12= Zhrf12:gsub('W','Ẃ')
Zhrf12= Zhrf12:gsub('e','Ἕ')
Zhrf12= Zhrf12:gsub('E','Ἕ')
Zhrf12= Zhrf12:gsub('r','Ȓ')
Zhrf12= Zhrf12:gsub('R','Ȓ')
Zhrf12= Zhrf12:gsub('t','Ҭ')
Zhrf12= Zhrf12:gsub('T','Ҭ')
Zhrf12= Zhrf12:gsub('y','Ὓ')
Zhrf12= Zhrf12:gsub('Y','Ὓ')
Zhrf12= Zhrf12:gsub('u','Ȗ')
Zhrf12= Zhrf12:gsub('U','Ȗ')
Zhrf12= Zhrf12:gsub('i','Ἷ')
Zhrf12= Zhrf12:gsub('I','Ἷ')
Zhrf12= Zhrf12:gsub('o','Ὃ')
Zhrf12= Zhrf12:gsub('O','Ὃ')
Zhrf12= Zhrf12:gsub('p','Ƥ')
Zhrf12= Zhrf12:gsub('P','Ƥ')
Zhrf12= Zhrf12:gsub('a','ᾋ')
Zhrf12= Zhrf12:gsub('A','ᾋ')
Zhrf12= Zhrf12:gsub('s','Ṩ')
Zhrf12= Zhrf12:gsub('S','Ṩ')
Zhrf12= Zhrf12:gsub('d','Ɖ')
Zhrf12= Zhrf12:gsub('D','Ɖ')
Zhrf12= Zhrf12:gsub('f','Ғ')
Zhrf12= Zhrf12:gsub('F','Ғ')
Zhrf12= Zhrf12:gsub('g','Ɠ')
Zhrf12= Zhrf12:gsub('G','Ɠ')
Zhrf12= Zhrf12:gsub('h','Ἤ')
Zhrf12= Zhrf12:gsub('H','Ἤ')
Zhrf12= Zhrf12:gsub('j','Ј')
Zhrf12= Zhrf12:gsub('J','Ј')
Zhrf12= Zhrf12:gsub('k','Ḱ')
Zhrf12= Zhrf12:gsub('K','Ḱ')
Zhrf12= Zhrf12:gsub('L','Ŀ')
Zhrf12= Zhrf12:gsub('l','Ŀ')
Zhrf12= Zhrf12:gsub('z','Ẕ')
Zhrf12= Zhrf12:gsub('Z','Ẕ')
Zhrf12= Zhrf12:gsub('x','Ẋ')
Zhrf12= Zhrf12:gsub('X','Ẋ')
Zhrf12= Zhrf12:gsub('c','Ƈ')
Zhrf12= Zhrf12:gsub('C','Ƈ')
Zhrf12= Zhrf12:gsub('v','V')
Zhrf12= Zhrf12:gsub('V','V')
Zhrf12= Zhrf12:gsub('b','ϐ')
Zhrf12= Zhrf12:gsub('B','ϐ')
Zhrf12= Zhrf12:gsub('n','Ɲ')
Zhrf12= Zhrf12:gsub('N','Ɲ')
Zhrf12= Zhrf12:gsub('m','Ṃ')
Zhrf12= Zhrf12:gsub('M','Ṃ')


local Text_Zhrfa = "1- "..Zhrf
.."\n2- "..Zhrf2
.."\n3- "..Zhrf3
.."\n4- "..Zhrf4
.."\n5- "..Zhrf5
.."\n6- "..Zhrf6
.."\n7- "..Zhrf7
.."\n8- "..Zhrf8
.."\n9- "..Zhrf9
.."\n10- "..Zhrf10
.."\n11- "..Zhrf11
.."\n12- "..Zhrf12
sendMsg(msg.chat_id,msg.id,Flter_Markdown(Text_Zhrfa))
return false
end
end
return{
Boss = {}
dboss = dboss
}
